### ISSUE TITLE
io-table 组件表头支持模板定义

### ISSUE THREAD

**Issue by AlexanderChen1989** [idcos/antd-ember#19]
现在io-table组件的数据支持通过模板定义，但是table header不支持
![image](https://cloud.githubusercontent.com/assets/2957936/14699224/9b50363a-07c8-11e6-8a36-2e53cd704b9d.png)

**Comment by 6174** [comment]
header template 已支持 ， 指定 headerTemplate 属性

eg：

``` javascript
  columns = [{
        "propertyName": "id",
        "title": "ID",
        "headerTemplate": "snippets/city-header-template"
    }]
```
