### ISSUE TITLE
应用中心中应用系统名称超过12个字符时导致应用卡片样式出现问题

### ISSUE THREAD

**Issue by liucy1983** [idcos/antd-ember#43]
应用中心中应用系统名称超过12个字符，且字面宽度达到1800时，同一行有6个卡片。
此时，超过12个字符的应用名称会换行，导致下一行卡片只有最后一个有内容，前面5个的位置均为空白

**Comment by 6174** [comment]
这个是业务bug， 在钉钉群里边说吧
