### ISSUE TITLE
io-table

### ISSUE THREAD

**Issue by xibolun** [idcos/antd-ember#47]
- 现在表格操作列里面引入模板太多，做成通用的模板，其他的做为参数传递
- 表格数据支持左右和上下滚动条，宽高可控

**Comment by 6174** [comment]
**问题1：**
  表格引入模板太多， 做成通用模板， 这个不是在 table 组件内做， 而是在 业务里边做， 自定义参数同理。 

**问题2：**
    已提交代码到 develop 分支， 支持了 固定 Header 模式，添加 useFixedHeader=true  即可使用， 水平滚动的场景可复杂可简单，目前来说通过外部容器添加 css 就可以。高度也是，高度的控制也交给 css 来设置吧。
