### ISSUE TITLE
用户可输入下拉框组件

### ISSUE THREAD

**Issue by liucy1983** [idcos/antd-ember#49]
当前下拉框组件中，用户只可从预定义的数据源中选择。
希望可以有一个支持用户输入内容，录入时模糊搜索数据源的内容提示，用户可选择具体数据，或可填入与数据源不同的内容（开发可根据需要是否限制在数据源内）

类似于这个样子：https://select2.github.io/examples.html#multiple

**Comment by 6174** [comment]
支持自定义搜索过滤以及 输入下拉提示两种方式， http://idcos.github.io/antd-ember/#/document/select
