### ISSUE TITLE
自定义数据校验

### ISSUE THREAD

**Issue by ygmpkk** [idcos/antd-ember#9]
需要自定义函数来校验数据字段，如
1. 校验数据的唯一性
2. Ajax请求校验数据是否存在

**Comment by 6174** [comment]
目前扩展自定义校验只能扩展 `Vaidatator.VALIDATORS` 对象， 可以通过   `$.fn.validator.Constructor.VALIDATORS` 获取,  如：

``` javascript
$.fn.validator.Constructor.VALIDATORS.mycustomvalidator = function($el) {
    var val = $el.data('mycustomvalidator');
   //..... some logic
   //  return true or false;
}
在组件中设置 **data-mycustomvalidator="val" 属性**
```

**Comment by 6174** [comment]
对于异步的情况， 虽然可以通过 data-remote 来做校验， 但是这样没次改动都会调用这个接口， 建议在提交的时候所有需要异步校验的数据统一做一次异步校验， 再将校验结果返回来提示。
